<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Artisan;
use App\Services\SSLService;

class SetupPanelDomain extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'npanel:setup-domain {domain}';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Setup a custom domain for the nPanel with SSL certificate';

    protected SSLService $sslService;

    public function __construct(SSLService $sslService)
    {
        parent::__construct();
        $this->sslService = $sslService;
    }

    /**
     * Execute the console command.
     */
    public function handle()
    {
        $domain = $this->argument('domain');

        // Validate domain format
        if (!preg_match('/^[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,}$/i', $domain)) {
            $this->error("Invalid domain format: {$domain}");
            return 1;
        }

        $this->info("Setting up nPanel domain: {$domain}");
        $this->newLine();

        // Step 1: Check DNS
        if (!$this->confirmDNS($domain)) {
            return 1;
        }

        // Step 2: Generate Nginx configuration
        if (!$this->generateNginxConfig($domain)) {
            return 1;
        }

        // Step 3: Test Nginx configuration
        if (!$this->testNginxConfig()) {
            return 1;
        }

        // Step 4: Reload Nginx
        if (!$this->reloadNginx()) {
            return 1;
        }

        // Step 5: Issue SSL certificate
        if (!$this->issueSSLCertificate($domain)) {
            $this->warn("SSL certificate issuance failed. You can try again later with:");
            $this->warn("  sudo /root/.acme.sh/acme.sh --issue -d {$domain} -w " . base_path('public'));
            $this->newLine();
        }

        // Step 6: Update .env file
        if (!$this->updateEnvFile($domain)) {
            return 1;
        }

        $this->newLine();
        $this->info("✓ Panel domain setup completed successfully!");
        $this->info("  Access your panel at: https://{$domain}");
        $this->newLine();
        $this->comment("Next steps:");
        $this->comment("  1. Go to Settings > System");
        $this->comment("  2. Verify the Panel URL is set to: https://{$domain}");
        $this->comment("  3. Test access via the new domain");

        return 0;
    }

    /**
     * Confirm DNS is pointing to this server
     */
    protected function confirmDNS(string $domain): bool
    {
        $this->info("Step 1: DNS Verification");

        // Get server IP
        $serverIp = trim(shell_exec("curl -s ifconfig.me"));
        
        // Resolve domain
        $domainIp = gethostbyname($domain);

        if ($domainIp === $domain) {
            $this->error("✗ DNS not configured: {$domain} does not resolve");
            $this->comment("  Please add an A record pointing to: {$serverIp}");
            return false;
        }

        if ($domainIp !== $serverIp) {
            $this->warn("⚠ DNS mismatch:");
            $this->warn("  Domain {$domain} resolves to: {$domainIp}");
            $this->warn("  Server IP is: {$serverIp}");
            
            if (!$this->confirm('Continue anyway?', false)) {
                return false;
            }
        } else {
            $this->info("✓ DNS correctly configured: {$domain} → {$serverIp}");
        }

        return true;
    }

    /**
     * Generate Nginx configuration for panel domain
     */
    protected function generateNginxConfig(string $domain): bool
    {
        $this->info("Step 2: Generating Nginx configuration");

        $panelRoot = base_path('public');
        $configPath = config('npanel.nginx_sites_available') . "/{$domain}.conf";

        $config = <<<NGINX
# nPanel Domain Configuration - {$domain}
# Generated by: php artisan npanel:setup-domain {$domain}

server {
    listen 80;
    listen [::]:80;
    server_name {$domain};

    root {$panelRoot};
    index index.php index.html;

    # Let's Encrypt ACME Challenge
    location ^~ /.well-known/acme-challenge/ {
        allow all;
        default_type "text/plain";
        root {$panelRoot};
    }

    # Redirect to HTTPS (will be enabled after SSL cert is issued)
    # return 301 https://\$server_name\$request_uri;

    # Temporary: Allow HTTP access for initial setup
    location / {
        try_files \$uri \$uri/ /index.php?\$query_string;
    }

    location ~ \\.php$ {
        fastcgi_pass unix:/var/run/php/php8.3-fpm.sock;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME \$document_root\$fastcgi_script_name;
        include fastcgi_params;
    }

    # Deny access to hidden files
    location ~ /\\. {
        deny all;
    }
}

# HTTPS Server (uncomment after SSL certificate is issued)
# server {
#     listen 443 ssl http2;
#     listen [::]:443 ssl http2;
#     server_name {$domain};
#
#     ssl_certificate /etc/letsencrypt/live/{$domain}/fullchain.pem;
#     ssl_certificate_key /etc/letsencrypt/live/{$domain}/privkey.pem;
#     ssl_protocols TLSv1.2 TLSv1.3;
#     ssl_ciphers HIGH:!aNULL:!MD5;
#     ssl_prefer_server_ciphers on;
#
#     root {$panelRoot};
#     index index.php index.html;
#
#     location / {
#         try_files \$uri \$uri/ /index.php?\$query_string;
#     }
#
#     location ~ \\.php$ {
#         fastcgi_pass unix:/var/run/php/php8.3-fpm.sock;
#         fastcgi_index index.php;
#         fastcgi_param SCRIPT_FILENAME \$document_root\$fastcgi_script_name;
#         include fastcgi_params;
#     }
#
#     location ~ /\\. {
#         deny all;
#     }
# }
NGINX;

        // Write config to temp file first
        $tempPath = sys_get_temp_dir() . "/{$domain}.conf";
        File::put($tempPath, $config);

        // Move with sudo
        $escapedTemp = escapeshellarg($tempPath);
        $escapedTarget = escapeshellarg($configPath);
        exec("sudo mv {$escapedTemp} {$escapedTarget}", $output, $returnVar);

        if ($returnVar !== 0) {
            $this->error("✗ Failed to write Nginx configuration");
            return false;
        }

        // Create symlink to enable site
        $symlinkPath = config('npanel.nginx_sites_enabled') . "/{$domain}.conf";
        $escapedSymlink = escapeshellarg($symlinkPath);
        exec("sudo ln -sf {$escapedTarget} {$escapedSymlink}", $output, $returnVar);

        if ($returnVar !== 0) {
            $this->error("✗ Failed to enable site");
            return false;
        }

        $this->info("✓ Nginx configuration created: {$configPath}");
        return true;
    }

    /**
     * Test Nginx configuration
     */
    protected function testNginxConfig(): bool
    {
        $this->info("Step 3: Testing Nginx configuration");

        exec('sudo nginx -t 2>&1', $output, $returnVar);

        if ($returnVar !== 0) {
            $this->error("✗ Nginx configuration test failed:");
            foreach ($output as $line) {
                $this->error("  {$line}");
            }
            return false;
        }

        $this->info("✓ Nginx configuration is valid");
        return true;
    }

    /**
     * Reload Nginx
     */
    protected function reloadNginx(): bool
    {
        $this->info("Step 4: Reloading Nginx");

        exec('sudo systemctl reload nginx 2>&1', $output, $returnVar);

        if ($returnVar !== 0) {
            $this->error("✗ Failed to reload Nginx");
            return false;
        }

        $this->info("✓ Nginx reloaded successfully");
        return true;
    }

    /**
     * Issue SSL certificate via Let's Encrypt
     */
    protected function issueSSLCertificate(string $domain): bool
    {
        $this->info("Step 5: Issuing SSL certificate");

        $acmePath = config('npanel.acme_sh_path');
        $webroot = base_path('public');

        $command = "sudo {$acmePath} --issue -d {$domain} -w {$webroot} 2>&1";
        exec($command, $output, $returnVar);

        if ($returnVar !== 0) {
            // Check if certificate already exists
            if (File::exists("/root/.acme.sh/{$domain}_ecc/fullchain.cer")) {
                $this->warn("⚠ Certificate already exists, installing it...");
            } else {
                $this->error("✗ SSL certificate issuance failed");
                foreach ($output as $line) {
                    $this->error("  {$line}");
                }
                return false;
            }
        }

        // Install certificate
        $certDir = "/etc/letsencrypt/live/{$domain}";
        exec("sudo mkdir -p {$certDir}", $output, $returnVar);

        $installCommand = "sudo {$acmePath} --install-cert -d {$domain} --ecc " .
            "--cert-file {$certDir}/cert.pem " .
            "--key-file {$certDir}/privkey.pem " .
            "--fullchain-file {$certDir}/fullchain.pem " .
            "--reloadcmd 'systemctl reload nginx' 2>&1";

        exec($installCommand, $output, $returnVar);

        if ($returnVar !== 0) {
            $this->error("✗ Failed to install SSL certificate");
            return false;
        }

        // Update Nginx config to enable HTTPS
        $this->enableHTTPS($domain);

        $this->info("✓ SSL certificate issued and installed");
        return true;
    }

    /**
     * Enable HTTPS in Nginx config
     */
    protected function enableHTTPS(string $domain): void
    {
        $configPath = config('npanel.nginx_sites_available') . "/{$domain}.conf";
        
        if (!File::exists($configPath)) {
            return;
        }

        $config = File::get($configPath);

        // Replace the entire HTTP server block with redirect
        $httpBlock = <<<'NGINX'
server {
    listen 80;
    listen [::]:80;
    server_name DOMAIN_NAME;
    
    # Redirect to HTTPS
    return 301 https://$server_name$request_uri;
}
NGINX;
        $httpBlock = str_replace('DOMAIN_NAME', $domain, $httpBlock);

        // Replace HTTP server block
        $config = preg_replace(
            '/server\s*\{[^}]*listen\s+80[^}]*\}/s',
            $httpBlock,
            $config,
            1
        );

        // Remove comment markers from HTTPS block
        $config = preg_replace('/^\s*#\s*server\s*\{/m', 'server {', $config);
        $config = preg_replace('/^\s*#\s*(listen\s+443)/m', '    $1', $config);
        $config = preg_replace('/^\s*#\s*(listen\s+\[::\]:443)/m', '    $1', $config);
        $config = preg_replace('/^\s*#\s*(server_name\s+' . preg_quote($domain, '/') . ')/m', '    $1', $config);
        $config = preg_replace('/^\s*#\s*(ssl_)/m', '    $1', $config);
        $config = preg_replace('/^\s*#\s*(root\s+)/m', '    $1', $config);
        $config = preg_replace('/^\s*#\s*(index\s+)/m', '    $1', $config);
        $config = preg_replace('/^\s*#\s*(location)/m', '    $1', $config);
        $config = preg_replace('/^\s*#\s*\}/m', '}', $config);
        
        // Fix indentation inside uncommented blocks
        $lines = explode("\n", $config);
        $inHttpsBlock = false;
        $fixedLines = [];
        
        foreach ($lines as $line) {
            if (preg_match('/listen 443/', $line)) {
                $inHttpsBlock = true;
            }
            if ($inHttpsBlock && preg_match('/^#/', $line)) {
                $line = preg_replace('/^#\s*/', '        ', $line);
            }
            if ($inHttpsBlock && preg_match('/^\}/', $line)) {
                $inHttpsBlock = false;
            }
            $fixedLines[] = $line;
        }
        
        $config = implode("\n", $fixedLines);

        // Write updated config
        $tempPath = sys_get_temp_dir() . "/{$domain}.conf";
        File::put($tempPath, $config);
        
        $escapedTemp = escapeshellarg($tempPath);
        $escapedTarget = escapeshellarg($configPath);
        exec("sudo mv {$escapedTemp} {$escapedTarget}");

        // Reload Nginx
        exec('sudo systemctl reload nginx 2>&1');
    }

    /**
     * Update .env file with panel URL
     */
    protected function updateEnvFile(string $domain): bool
    {
        $this->info("Step 6: Updating .env configuration");

        $envPath = base_path('.env');
        
        if (!File::exists($envPath)) {
            $this->error("✗ .env file not found");
            return false;
        }

        $envContent = File::get($envPath);
        $panelUrl = "https://{$domain}";

        // Check if NPANEL_URL exists
        if (preg_match('/^NPANEL_URL=/m', $envContent)) {
            // Update existing
            $envContent = preg_replace(
                '/^NPANEL_URL=.*/m',
                "NPANEL_URL={$panelUrl}",
                $envContent
            );
        } else {
            // Add new
            $envContent .= "\n# Panel Access URL\nNPANEL_URL={$panelUrl}\n";
        }

        File::put($envPath, $envContent);

        // Clear config cache
        Artisan::call('config:clear');

        $this->info("✓ Panel URL configured: {$panelUrl}");
        return true;
    }
}
