#!/bin/bash

###############################################################################
# phpMyAdmin Installation & Configuration Script for nPanel SSO
###############################################################################

set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

print_status() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

print_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

print_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

print_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

# Check if running as root
if [ "$EUID" -ne 0 ]; then
    print_error "Please run as root"
    exit 1
fi

echo ""
echo "==========================================="
echo "  phpMyAdmin Installation for nPanel"
echo "==========================================="
echo ""

# Install phpMyAdmin
print_status "Installing phpMyAdmin..."
apt-get update
apt-get install -y phpmyadmin

print_success "phpMyAdmin installed"

# Configure phpMyAdmin for SSO
print_status "Configuring phpMyAdmin for SSO authentication..."

# Backup original config
if [ -f /etc/phpmyadmin/config.inc.php ]; then
    cp /etc/phpmyadmin/config.inc.php /etc/phpmyadmin/config.inc.php.backup
    print_status "Original config backed up"
fi

# Create SSO configuration
cat > /etc/phpmyadmin/config.inc.php << 'EOF'
<?php
/**
 * phpMyAdmin configuration for nPanel SSO
 * Generated by nPanel install script
 */

// Servers configuration
$i = 0;

// Server 1 - SSO Authentication
$i++;
$cfg['Servers'][$i]['auth_type'] = 'signon';
$cfg['Servers'][$i]['SignonSession'] = 'phpMyAdmin_sso';
$cfg['Servers'][$i]['SignonURL'] = '/phpmyadmin-sso.php';
$cfg['Servers'][$i]['LogoutURL'] = '/dashboard';
$cfg['Servers'][$i]['host'] = '127.0.0.1';
$cfg['Servers'][$i]['port'] = '3306';
$cfg['Servers'][$i]['compress'] = false;
$cfg['Servers'][$i]['AllowNoPassword'] = false;

// phpMyAdmin configuration storage settings (optional)
// Uncomment and configure if you want to use phpMyAdmin configuration storage
// $cfg['Servers'][$i]['pmadb'] = 'phpmyadmin';
// $cfg['Servers'][$i]['bookmarktable'] = 'pma__bookmark';
// $cfg['Servers'][$i]['relation'] = 'pma__relation';
// $cfg['Servers'][$i]['table_info'] = 'pma__table_info';
// $cfg['Servers'][$i]['table_coords'] = 'pma__table_coords';
// $cfg['Servers'][$i]['pdf_pages'] = 'pma__pdf_pages';
// $cfg['Servers'][$i]['column_info'] = 'pma__column_info';
// $cfg['Servers'][$i]['history'] = 'pma__history';
// $cfg['Servers'][$i]['table_uiprefs'] = 'pma__table_uiprefs';
// $cfg['Servers'][$i]['tracking'] = 'pma__tracking';
// $cfg['Servers'][$i]['userconfig'] = 'pma__userconfig';
// $cfg['Servers'][$i]['recent'] = 'pma__recent';
// $cfg['Servers'][$i]['favorite'] = 'pma__favorite';
// $cfg['Servers'][$i]['users'] = 'pma__users';
// $cfg['Servers'][$i]['usergroups'] = 'pma__usergroups';
// $cfg['Servers'][$i]['navigationhiding'] = 'pma__navigationhiding';
// $cfg['Servers'][$i]['savedsearches'] = 'pma__savedsearches';
// $cfg['Servers'][$i]['central_columns'] = 'pma__central_columns';
// $cfg['Servers'][$i]['designer_settings'] = 'pma__designer_settings';
// $cfg['Servers'][$i]['export_templates'] = 'pma__export_templates';

// General settings
$cfg['blowfish_secret'] = '$(openssl rand -base64 32)';
$cfg['DefaultLang'] = 'en';
$cfg['ServerDefault'] = 1;
$cfg['UploadDir'] = '/var/lib/phpmyadmin/upload';
$cfg['SaveDir'] = '/var/lib/phpmyadmin/save';
$cfg['TempDir'] = '/var/lib/phpmyadmin/tmp';

// Security settings
$cfg['LoginCookieValidity'] = 3600; // 1 hour
$cfg['LoginCookieRecall'] = false;
$cfg['AllowThirdPartyFraming'] = false;

// Disable version check (privacy)
$cfg['VersionCheck'] = false;

// Theme
$cfg['ThemeDefault'] = 'pmahomme';

// Features
$cfg['ShowPhpInfo'] = false;
$cfg['ShowServerInfo'] = true;
$cfg['ShowStats'] = true;
$cfg['ShowChgPassword'] = false; // Managed by nPanel
$cfg['ShowCreateDb'] = false; // Managed by nPanel
$cfg['AllowUserDropDatabase'] = false; // Managed by nPanel

// SQL query settings
$cfg['MaxRows'] = 50;
$cfg['Order'] = 'ASC';

// Export/Import settings
$cfg['Export']['method'] = 'quick';
$cfg['Import']['charset'] = 'utf-8';

// Console mode
$cfg['Console']['Mode'] = 'collapse';
EOF

print_success "phpMyAdmin configured for SSO"

# Create required directories
print_status "Creating phpMyAdmin directories..."
mkdir -p /var/lib/phpmyadmin/upload
mkdir -p /var/lib/phpmyadmin/save
mkdir -p /var/lib/phpmyadmin/tmp
chown -R www-data:www-data /var/lib/phpmyadmin
chmod 750 /var/lib/phpmyadmin/{upload,save,tmp}
print_success "Directories created"

# Configure Nginx for phpMyAdmin
print_status "Configuring Nginx virtual host..."

cat > /etc/nginx/sites-available/phpmyadmin.conf << 'EOF'
# phpMyAdmin Nginx configuration for nPanel
# Accessible only from localhost by default for security

server {
    listen 80;
    server_name localhost;

    root /usr/share/phpmyadmin;
    index index.php index.html index.htm;

    # Security headers
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-XSS-Protection "1; mode=block" always;

    # Logs
    access_log /var/log/nginx/phpmyadmin-access.log;
    error_log /var/log/nginx/phpmyadmin-error.log;

    location / {
        try_files $uri $uri/ =404;
    }

    location ~ \.php$ {
        include snippets/fastcgi-php.conf;
        fastcgi_pass unix:/var/run/php/php8.3-fpm.sock;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
    }

    # Deny access to hidden files
    location ~ /\. {
        deny all;
    }

    # Deny access to setup
    location ~ ^/(doc|sql|setup)/ {
        deny all;
    }
}
EOF

# Enable site
ln -sf /etc/nginx/sites-available/phpmyadmin.conf /etc/nginx/sites-enabled/phpmyadmin.conf

# Test and reload Nginx
print_status "Testing Nginx configuration..."
nginx -t

if [ $? -eq 0 ]; then
    print_success "Nginx configuration valid"
    systemctl reload nginx
    print_success "Nginx reloaded"
else
    print_error "Nginx configuration test failed"
    exit 1
fi

echo ""
echo "==========================================="
print_success "phpMyAdmin Installation Complete!"
echo "==========================================="
echo ""
echo "Configuration:"
echo "- Authentication: SSO via nPanel"
echo "- Access URL: http://localhost/phpmyadmin"
echo "- SSO Script: /var/www/npanel/public/phpmyadmin-sso.php"
echo "- Config: /etc/phpmyadmin/config.inc.php"
echo ""
echo "Important:"
echo "1. phpMyAdmin is accessible via nPanel's Database Manager"
echo "2. Direct access requires SSO token (5-minute TTL)"
echo "3. Users are automatically logged into their specific database"
echo ""
echo "Security:"
echo "- SSO tokens are single-use and expire after 5 minutes"
echo "- Each session is isolated to one database"
echo "- Password changes are managed by nPanel, not phpMyAdmin"
echo ""
